### Proxy ###

[grpc-proxy]
listeners = [
  { addr = "127.0.0.1:8008" }
  { addr = "127.0.0.1:8080", cert-path = "cert.pem", key-path = "key.pem" }
  { addr = "[::1]:8888", cert-path = "cert.pem", key-path = "key.pem" }
]

### Paths ###

[[path."/test.Test/Test1"]]
urls = [
  "http://127.0.0.1:9000",
  "https://127.0.0.1:9009",
]

[[path."/test.Test/Test2"]]
urls = [ "http://127.0.0.1:9090" ]

[[path."/test.Test/Test3"]]
urls = [
  "http://127.0.0.1:9000"
  "https://127.0.0.1:9009"
  "http://127.0.0.1:9090"
  "https://127.0.0.1:9999"
]
